# Generated by Django 5.2.17 on 2026-09-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_demandereinitialisation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classe",
            options={
                "ordering": ["name"],
                "verbose_name": "classe",
                "verbose_name_plural": "classes",
            },
        ),
        migrations.AlterField(
            model_name="classe",
            name="name",
            field=models.CharField(max_length=100, verbose_name="nom"),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="nom affiché"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("prof", "Professeur"), ("eleve", "Élève")],
                default="eleve",
                max_length=10,
                verbose_name="rôle",
            ),
        ),
    ]
