# Generated by Django 6.0.7 on 2026-09-18 17:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guid",
                    models.CharField(default=uuid.uuid4, max_length=64, unique=True),
                ),
                (
                    "question",
                    models.TextField(
                        help_text='HTML autorisé, y compris <img src="...">'
                    ),
                ),
                (
                    "reponse",
                    models.TextField(
                        help_text='HTML autorisé, y compris <img src="...">'
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Séparés par des espaces, comme Anki",
                        max_length=300,
                    ),
                ),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        help_text="Étudiant à l'origine de la note, si ajoutée après l'import initial",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes_creees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="anki_review.deck",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.CharField(
                        choices=[
                            ("new", "Nouvelle"),
                            ("learning", "En apprentissage"),
                            ("review", "En révision"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("intervalle_jours", models.FloatField(default=0)),
                ("facteur_facilite", models.FloatField(default=2.5)),
                ("repetitions", models.PositiveIntegerField(default=0)),
                (
                    "echecs",
                    models.PositiveIntegerField(
                        default=0, help_text="Nombre de fois répondu 'Again'"
                    ),
                ),
                (
                    "prochaine_revision",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("derniere_revision", models.DateTimeField(blank=True, null=True)),
                ("suspendue", models.BooleanField(default=False)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cartes_anki",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="anki_review.note",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["etudiant", "prochaine_revision"],
                        name="anki_review_etudian_04097d_idx",
                    )
                ],
                "unique_together": {("note", "etudiant")},
            },
        ),
    ]
