# Generated by Django 6.0.7 on 2026-09-19 06:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="partagee_avec_classe",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Propriétaire de cette copie de la note (prof ou étudiant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes_creees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="guid",
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name="note",
            unique_together={("guid", "cree_par")},
        ),
    ]
