# Generated by Django 6.0.7 on 2026-09-19 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0002_note_partagee_avec_classe_alter_note_cree_par_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="cree_par",
            field=models.ForeignKey(
                blank=True,
                help_text="Propriétaire du paquet (prof ou étudiant) — seul lui (ou un prof) peut le modifier/supprimer",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decks_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
