# Generated by Django 6.0.7 on 2026-09-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0003_deck_cree_par"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="matiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physique", "Physique"),
                    ("mathematiques", "Mathématiques"),
                    ("chimie", "Chimie"),
                    ("anglais", "Anglais"),
                    ("lettres-philosophie", "Lettres-Philosophie"),
                    ("allemand", "Allemand"),
                    ("espagnol", "Espagnol"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
