# Generated by Django 6.0.7 on 2026-09-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0004_deck_matiere"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="officielle",
            field=models.BooleanField(default=True),
        ),
    ]
