# Generated by Django 6.0.7 on 2026-09-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0005_note_officielle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="officielle",
        ),
    ]
