# Generated by Django 6.0.7 on 2026-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0006_remove_note_officielle"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="titre",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
