# Generated by Django 6.0.7 on 2026-09-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0007_note_titre"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="note_miroir",
            field=models.OneToOneField(
                blank=True,
                help_text="Autre moitié d'une paire recto-verso/verso-recto — modifier l'une met à jour l'autre (inversée).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="anki_review.note",
            ),
        ),
    ]
