# Generated by Django 6.0.7 on 2026-09-22 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0008_note_note_miroir"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="titre",
        ),
    ]
