# Generated by Django 6.0.7 on 2026-09-23 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0009_remove_note_titre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="note",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="card",
            name="cree_le",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="PropositionModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(
                        help_text='HTML autorisé, y compris <img src="...">'
                    ),
                ),
                (
                    "reponse",
                    models.TextField(
                        help_text='HTML autorisé, y compris <img src="...">'
                    ),
                ),
                ("tags", models.CharField(blank=True, max_length=300)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("acceptee", "Acceptée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=10,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("traitee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions_faites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="propositions",
                        to="anki_review.note",
                    ),
                ),
            ],
            options={
                "ordering": ["-cree_le"],
            },
        ),
    ]
