# Generated by Django 6.0.7 on 2026-09-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anki_review", "0010_alter_note_unique_together_card_cree_le_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="matiere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("physique", "Physique"),
                    ("mathematiques", "Mathématiques"),
                    ("chimie", "Chimie"),
                    ("informatique", "Informatique"),
                    ("sii", "SII"),
                    ("anglais", "Anglais"),
                    ("lettres-philosophie", "Lettres-Philosophie"),
                    ("allemand", "Allemand"),
                    ("espagnol", "Espagnol"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
