# Generated by Django 5.2.17 on 2026-09-23 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anki_review', '0011_alter_deck_matiere'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('revision', 'Révision'), ('ajout', 'Ajout'), ('recuperation', 'Récupération')], max_length=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('carte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activites', to='anki_review.card')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites_anki', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='anki_review_date_29feb1_idx')],
            },
        ),
    ]
