# Generated by Django 6.0.7 on 2026-07-09 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('statement', models.TextField(help_text="Énoncé de l'exercice (Markdown simple accepté).")),
                ('starter_code', models.TextField(blank=True, help_text="Code de départ affiché dans l'éditeur (ex: l'en-tête de la fonction).")),
                ('function_name', models.CharField(help_text="Nom de la fonction que l'étudiant doit écrire (ex: 'triple').", max_length=100)),
                ('solution_code', models.TextField(help_text="Code de correction : une implémentation complète et correcte de la fonction. Le résultat attendu de chaque test (ci-dessous) est calculé automatiquement en exécutant ce code — tu n'as qu'à indiquer les arguments à tester.")),
            ],
            options={
                'ordering': ['theme__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exercises.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.JSONField(default=list, help_text='Arguments à passer à la fonction, en JSON. Ex : [2, 3] ou [[1, 2, 3]] pour un seul argument liste.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exercises.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('theme', 'slug')},
        ),
    ]