# Generated by Django 6.0.7 on 2026-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='args',
            field=models.TextField(default='[]', help_text="Arguments à passer à la fonction, en syntaxe Python (pas JSON). Ex : [2, 3]  ou  ['bonjour']  ou  [True, None]  ou  [{'a': 1, 'b': 2}]  ou  [[1, 2, 3]]."),
        ),
    ]
