# Generated by Django 6.0.7 on 2026-07-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='function_name',
            field=models.CharField(blank=True, help_text="Nom de la fonction que l'étudiant doit écrire (ex: 'triple'). Si rempli, les cas de test ci-dessous sont utilisés automatiquement.", max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_cases',
            field=models.JSONField(blank=True, default=list, help_text='Liste de cas de test, format JSON. Chaque cas : {"args": [valeurs des paramètres], "expected": résultat attendu}. Exemple pour une fonction triple(n) : [{"args": [2], "expected": 6}, {"args": [0], "expected": 0}, {"args": [-5], "expected": -15}]'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(blank=True, help_text="Code de départ affiché dans l'éditeur (ex: l'en-tête de la fonction)."),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='test_code',
            field=models.TextField(blank=True, help_text="Avancé : code Python de correction écrit à la main, exécuté après le code de l'étudiant. Doit définir une liste __RESULTS__ de tuples (bool_ok, message). Utilisé uniquement si 'function_name' est vide (ex: pour tester une variable plutôt qu'une fonction)."),
        ),
    ]
