# Generated by Django 6.0.7 on 2026-07-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_testcase_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='kind',
            field=models.CharField(choices=[('python', 'Python (fonction)'), ('sql', 'SQL (requête)')], default='python', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sql_setup',
            field=models.TextField(blank=True, help_text="[SQL] Instructions SQL (CREATE TABLE + INSERT) qui créent les données de départ, rejouées à l'identique avant chaque tentative (base en mémoire, remise à zéro à chaque essai)."),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sql_solution',
            field=models.TextField(blank=True, help_text="[SQL] La requête SQL correcte. Le résultat attendu est calculé automatiquement en l'exécutant sur les données de sql_setup, puis comparé à la requête de l'étudiant."),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='function_name',
            field=models.CharField(blank=True, help_text="[Python] Nom de la fonction que l'étudiant doit écrire (ex: 'triple').", max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution_code',
            field=models.TextField(blank=True, help_text="[Python] Code de correction : une implémentation complète et correcte de la fonction. Le résultat attendu de chaque test (ci-dessous) est calculé automatiquement en exécutant ce code — tu n'as qu'à indiquer les arguments à tester."),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(blank=True, help_text="Code de départ affiché dans l'éditeur (l'en-tête de la fonction, ou un commentaire SQL)."),
        ),
    ]
