# Generated by Django 6.0.7 on 2026-07-08 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_function_name_exercise_test_cases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='exercise',
            name='solution_code',
            field=models.TextField(blank=True, help_text="Code de correction : une implémentation complète et correcte de la fonction. S'il est rempli, le résultat attendu de chaque test est calculé automatiquement en exécutant ce code — tu n'as qu'à indiquer les arguments à tester, pas le résultat."),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='function_name',
            field=models.CharField(blank=True, help_text="Nom de la fonction que l'étudiant doit écrire (ex: 'triple'). Si rempli, les tests ci-dessous (section 'Test cases') sont utilisés automatiquement.", max_length=100),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', models.JSONField(default=list, help_text='Arguments à passer à la fonction, en JSON. Ex : [2, 3] ou [[1, 2, 3]] pour un seul argument liste.')),
                ('expected', models.JSONField(blank=True, help_text="Résultat attendu — à remplir seulement si aucun 'code de correction' n'est fourni sur l'exercice.", null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exercises.exercise')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
