# Generated by Django 6.0.7 on 2026-07-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_kind_exercise_sql_setup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='sql_setup',
            field=models.TextField(blank=True, help_text="[SQL] Base de données partagée par défaut pour tous les exercices SQL de ce thème (instructions CREATE TABLE + INSERT). Un exercice peut définir son propre 'sql_setup' pour utiliser des données différentes ponctuellement, sinon celui du thème est utilisé."),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sql_setup',
            field=models.TextField(blank=True, help_text="[SQL] Optionnel : instructions SQL (CREATE TABLE + INSERT) propres à CET exercice, si tu veux des données différentes de celles du thème. Laisse vide pour réutiliser automatiquement le 'sql_setup' défini sur le thème."),
        ),
    ]
