# Generated by Django 6.0.7 on 2026-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_classe_user_role_user_classe"),
        ("exercises", "0008_theme_exercise_enabled_for_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="enabled_for_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classes pour lesquelles CET exercice précis est visible (en plus du thème, qui doit lui aussi être visible). Vide par défaut = invisible pour tout le monde : réglage à faire via la page /stats/visibilite/.",
                related_name="enabled_exercises",
                to="accounts.classe",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="enabled_for_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Classes pour lesquelles ce thème est visible. Vide par défaut = invisible pour tout le monde (y compris un nouveau thème fraîchement créé) : réglage à faire via la page /stats/visibilite/.",
                related_name="enabled_themes",
                to="accounts.classe",
            ),
        ),
        migrations.AlterField(
            model_name="theme",
            name="sql_setup",
            field=models.TextField(
                blank=True,
                help_text="[SQL] Base de données partagée par défaut pour tous les exercices SQL de ce thème (instructions CREATE TABLE + INSERT). Un exercice peut définir son propre 'sql_setup' pour utiliser des données différentes ponctuellement, sinon celui du thème est utilisé. Astuce : ajoute des commentaires SQL ('-- texte') après une table ou une colonne pour qu'ils apparaissent dans le résumé de schéma affiché aux étudiants.",
            ),
        ),
    ]
