# Generated by Django 5.2.17 on 2026-09-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0009_alter_exercise_enabled_for_classes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="extra_test_code",
            field=models.TextField(
                blank=True,
                help_text="[Python] Optionnel : code de test supplémentaire, exécuté après les tests habituels. Peut appeler __FN__(...) (remplacé automatiquement par le nom de la fonction de l'étudiant) et doit ajouter ses propres résultats à __RESULTS__ sous la forme (booléen_reussite, message, sortie_console) — voir les exercices existants pour des exemples (ex: vérifier qu'une structure de données n'est pas partagée par erreur, ou qu'une construction du langage précise n'est pas utilisée).",
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="require_recursive",
            field=models.BooleanField(
                default=False,
                help_text="[Python] Si coché, on vérifie en plus (analyse statique du code, sans l'exécuter) que la fonction de l'étudiant s'appelle bien elle-même — sinon l'exercice est refusé même si le résultat renvoyé est correct.",
            ),
        ),
    ]
