# Generated by Django 5.2.17 on 2026-09-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0013_vocabulaire_admin_fr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeaide",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
