# Generated by Django 5.2.17 on 2026-09-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0014_alter_demandeaide_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="sql_setup",
            field=models.TextField(
                blank=True,
                help_text="[SQL] Base de données partagée par défaut pour tous les exercices SQL de ce thème (instructions CREATE TABLE + INSERT). Un exercice peut définir son propre 'sql_setup' pour utiliser des données différentes ponctuellement, sinon celui du thème est utilisé. Ajouter des commentaires SQL ('-- texte') après une table ou une colonne pour qu'ils apparaissent dans le résumé de schéma affiché aux étudiants.",
                verbose_name="script SQL",
            ),
        ),
    ]
