# Generated by Django 5.2.17 on 2026-10-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0015_alter_theme_sql_setup_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="forbid_in_operator",
            field=models.BooleanField(
                default=False,
                help_text="[Python] Si coché, on vérifie en plus (analyse statique du code, sans l'exécuter) que le code de l'étudiant n'utilise pas l'opérateur de test d'appartenance « in » / « not in » (ex: 'mot in phrase'). La boucle 'for x in ...' reste autorisée. Sinon l'exercice est refusé même si le résultat renvoyé est correct.",
                verbose_name="opérateur « in » interdit",
            ),
        ),
    ]
