# Generated by Django 5.2.17 on 2026-10-03 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0016_exercise_forbid_in_operator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="forbid_in_operator",
        ),
    ]
