"""
Django settings for codexo project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Charge les variables depuis un fichier .env local s'il existe (développement uniquement).
# En production (Render), ce fichier n'existe pas : load_dotenv() ne fait alors rien,
# et les vraies variables d'environnement (définies dans l'interface Render) sont utilisées.
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-uuzn7)q=hw9q&a&7e3m1$9=^f3$%&_y4l7_+-e8z^!7nb0@4vw',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]
if DEBUG:
    ALLOWED_HOSTS += ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'exercises',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Ajouté le 06/09/2026 (refonte de l'authentification, voir contexte-technique.md) :
    # doit rester APRÈS AuthenticationMiddleware (a besoin de request.user déjà résolu).
    'accounts.middleware.ForcerChangementMotDePasseMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'codexo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'codexo.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'codexo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Dossier où vivent les fichiers que le serveur web doit pouvoir écrire (la base
# SQLite notamment). Séparé du code pour ne donner l'écriture qu'à cet endroit
# précis en production, jamais sur le reste du projet.

DATA_DIR = Path(os.environ.get('DJANGO_DATA_DIR', BASE_DIR / 'data'))
DATA_DIR.mkdir(parents=True, exist_ok=True)


import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{DATA_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Logging
# https://docs.djangoproject.com/en/6.0/topics/logging/
#
# Ajouté le 06/09/2026 : par défaut, Django n'affiche les erreurs sur la console
# que si DEBUG=True, et se contente sinon d'essayer de les envoyer par email aux
# adresses listées dans ADMINS (vide ici) — en prod, une erreur 500 ne laissait
# donc aujourd'hui absolument aucune trace consultable. Ce réglage remplace ce
# comportement par : la console (toujours, même en prod — utile si le process
# est supervisé par systemd/Apache, ses logs finissent dans le journal du
# service) + un fichier dédié dans DATA_DIR (persistant, lisible avec un simple
# tail/grep, avec rotation automatique pour ne pas grossir indéfiniment).
LOG_DIR = DATA_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'fichier': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 Mo par fichier...
            'backupCount': 5,             # ...avant rotation (django.log.1, .2, ...jusqu'à .5)
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Reprend TOUT ce qui passe par le logger "django" (dont les erreurs 500,
        # via son enfant "django.request" qui remonte ici par défaut) : remplace
        # entièrement la configuration par défaut de Django pour ce logger (voir
        # DEFAULT_LOGGING dans le code source de Django, fusionné avec ce
        # dictionnaire au démarrage).
        'django': {
            'handlers': ['console', 'fichier'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'theme_list'
LOGOUT_REDIRECT_URL = 'login'